jdbc.driver=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://127.0.0.1:3306/forum?serverTimezone=UTC
jdbc.username=root
jdbc.password=password
jdbc.maxActive=20
jdbc.minIdle=2
jdbc.maxIdle=60
jdbc.initialSize=2
jdbc.maxWait=60000
